http:
  port: 8080

apiEndpoints:
  productsApi:
    host: localhost
    paths: /products/*
  usersApi:
    host: localhost
    paths: /users/*
  ordersApi:
    host: localhost
    paths: /orders/*

serviceEndpoints:
  products:
    url: http://localhost:3001
  users:
    url: http://localhost:3002
  orders:
    url: http://localhost:3003

policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
  - jwt

pipelines:
  default:
    apiEndpoints:
      - productsApi
      - usersApi
      - ordersApi
    policies:
      # Uncomment `key-auth:` when instructed to in the Getting Started guide.
      # - key-auth:
      - proxy:
          - action:
              # Use the appropriate service endpoint based on the API being accessed
              serviceEndpoint: products
              changeOrigin: true  # Required if the services run on a different host or port
      - proxy:
          - action:
              serviceEndpoint: users
              changeOrigin: true
      - proxy:
          - action:
              serviceEndpoint: orders
              changeOrigin: true
      - jwt:
          - action:
              secretOrPublicKey: 'your-secret-key'  # Change this to your secret key
              checkCredentialExistence: true
              credentialsRequired: true
              algorithms:
                - HS256